spring:
  application:
    name: library-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  zipkin:
    base-url: http://localhost:9411

server:
  port: 8082

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: info
  endpoint:
    health:
      show-details: always 