spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/v1/book/**
        - id: library-service
          uri: lb://library-service
          predicates:
            - Path=/v1/library/**
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management: # Actuator endpoint'lerini yapilandir
  endpoints: #http://localhost:8888/actuator
    web:
      exposure:
        include: "*" # Tum end pointleri ekle
        exclude: info # info endpoint'ini ekleme


        #  `cloud:`: Bu bölüm, bulut altyap?s?na yönelik yap?land?rmalar? içerir.
        #
        #      - `gateway:`: Bu, a? geçidi (gateway) yap?land?rmas?n? belirtir.
        #
        #           - `routes:`: Bu, a? geçidi üzerinden yönlendirilecek hedefleri tan?mlar.
        #
        #                - `id: book-service`: Bu, yönlendirme için kullan?lan servisin kimli?ini tan?mlar.
        #
        #                         - `uri: lb://book-service`: Bu, hedef servisin URI'sini belirtir. "lb://" ifadesi, yük dengeleyici (load balancer) kullan?ld???n? gösterir.
        #
        #                         - `predicates:`: Bu, yönlendirmenin hangi ölçütlere göre yap?laca??n? belirtir.
        #
        #                              - `Path=/v1/book/**`: Bu, istek URL'sinin belirli bir desenle e?le?mesi gerekti?ini belirtir.
        #
        #     `discovery:`: Bu bölüm, servis ke?fi ile ilgili yap?land?rmalar? içerir.
        #
        #        - `locator:`: Bu, servislerin isimlerine göre otomatik olarak yönlendirilip yönlendirilmeyece?ini belirtir.
        #
        #             - `enabled: true`: Bu, isim tabanl? yönlendirme (service discovery locator) özelli?inin aktif oldu?unu belirtir.
        #
        #
        #
        #     `eureka:`: Bu bölüm, Eureka servis ke?fi için yap?land?rmalar? içerir.
        #
        #        - `client:`: Bu, Eureka istemci yap?land?rmas?n? içerir.
        #
        #             - `register-with-eureka: true`: Bu, servisin Eureka sunucusuna kaydolup kaydolmayaca??n? belirtir.
        #
        #             - `service-url:`: Bu, Eureka sunucusunun hizmet URL'sini belirtir.
        #
        #                  - `defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}`: Bu, varsay?lan Eureka sunucu adresini belirtir. E?er `EUREKA_URI` ortam de?i?keni tan?ml? de?ilse `http://localhost:8761/eureka` kullan?l?r.
        #
        #        - `instance:`: Bu, Eureka istemcisine ait örnek yap?land?rmalar?n? içerir.
        #
        #             - `prefer-ip-address: true`: Bu, Eureka?n?n hostname yerine IP adresini kullanmas?n? sa?lar.
